//======================================================================
//
// AsyncLoader.c - Dynamic Module Exporting
//
// This file is generated by GenLoader.py. Don't modify it.
// 2015-02-27 13:47:52
//
//======================================================================
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#if defined(WIN32) || defined(WIN64) || defined(_WIN32) || defined(_WIN64)
#include <windows.h>
#else
#include <unistd.h>
#include <dlfcn.h>
#endif
#include "AsyncLoader.h"


//======================================================================
// Type Of Interfaces
//======================================================================
typedef ANETAPI AsyncCore* (*_t_asn_core_new)(void);
typedef ANETAPI void (*_t_asn_core_delete)(AsyncCore * core);
typedef ANETAPI void (*_t_asn_core_wait)(AsyncCore * core, unsigned long millisec);
typedef ANETAPI void (*_t_asn_core_notify)(AsyncCore * core);
typedef ANETAPI long (*_t_asn_core_read)(AsyncCore * core, int * event, long * wparam, long * lparam, void * data, long size);
typedef ANETAPI long (*_t_asn_core_send)(AsyncCore * core, long hid, const void * ptr, long len);
typedef ANETAPI int (*_t_asn_core_close)(AsyncCore * core, long hid, int code);
typedef ANETAPI long (*_t_asn_core_send_vector)(AsyncCore * core, long hid, const void * vecptr [], const long veclen [], int count, int mask);
typedef ANETAPI long (*_t_asn_core_send_mask)(AsyncCore * core, long hid, const void * ptr, long len, int mask);
typedef ANETAPI long (*_t_asn_core_new_connect)(AsyncCore * core, const char * ip, int port, int header);
typedef ANETAPI long (*_t_asn_core_new_listen)(AsyncCore * core, const char * ip, int port, int header);
typedef ANETAPI long (*_t_asn_core_new_assign)(AsyncCore * core, int fd, int header, int check_estab);
typedef ANETAPI int (*_t_asn_core_post)(AsyncCore * core, long wparam, long lparam, const char * data, long size);
typedef ANETAPI int (*_t_asn_core_get_mode)(const AsyncCore * core, long hid);
typedef ANETAPI long (*_t_asn_core_get_tag)(const AsyncCore * core, long hid);
typedef ANETAPI void (*_t_asn_core_set_tag)(AsyncCore * core, long hid, long tag);
typedef ANETAPI long (*_t_asn_core_remain)(const AsyncCore * core, long hid);
typedef ANETAPI void (*_t_asn_core_limit)(AsyncCore * core, long limited, long maxsize);
typedef ANETAPI long (*_t_asn_core_node_head)(const AsyncCore * core);
typedef ANETAPI long (*_t_asn_core_node_next)(const AsyncCore * core, long hid);
typedef ANETAPI long (*_t_asn_core_node_prev)(const AsyncCore * core, long hid);
typedef ANETAPI int (*_t_asn_core_option)(AsyncCore * core, long hid, int opt, long value);
typedef ANETAPI int (*_t_asn_core_status)(AsyncCore * core, long hid, int opt);
typedef ANETAPI int (*_t_asn_core_rc4_set_skey)(AsyncCore * core, long hid, const unsigned char * key, int keylen);
typedef ANETAPI int (*_t_asn_core_rc4_set_rkey)(AsyncCore * core, long hid, const unsigned char * key, int keylen);
typedef ANETAPI void (*_t_asn_core_firewall)(AsyncCore * core, AsyncValidator v, void * user);
typedef ANETAPI void (*_t_asn_core_timeout)(AsyncCore * core, long seconds);
typedef ANETAPI int (*_t_asn_core_sockname)(const AsyncCore * core, long hid, char * out);
typedef ANETAPI int (*_t_asn_core_peername)(const AsyncCore * core, long hid, char * out);
typedef ANETAPI int (*_t_asn_core_disable)(AsyncCore * core, long hid, int value);
typedef ANETAPI int (*_t_asn_core_nfds)(const AsyncCore * core);
typedef ANETAPI AsyncNotify* (*_t_asn_notify_new)(int serverid);
typedef ANETAPI void (*_t_asn_notify_delete)(AsyncNotify * notify);
typedef ANETAPI void (*_t_asn_notify_wait)(AsyncNotify * notify, unsigned long millisec);
typedef ANETAPI void (*_t_asn_notify_wake)(AsyncNotify * notify);
typedef ANETAPI long (*_t_asn_notify_read)(AsyncNotify * notify, int * event, long * wparam, long * lparam, void * data, long maxsize);
typedef ANETAPI long (*_t_asn_notify_listen)(AsyncNotify * notify, const char * addr, int port, int flag);
typedef ANETAPI int (*_t_asn_notify_remove)(AsyncNotify * notify, long listenid, int code);
typedef ANETAPI void (*_t_asn_notify_change)(AsyncNotify * notify, int new_server_id);
typedef ANETAPI int (*_t_asn_notify_send)(AsyncNotify * notify, int sid, short cmd, const void * data, long size);
typedef ANETAPI int (*_t_asn_notify_close)(AsyncNotify * notify, int sid, int mode, int code);
typedef ANETAPI int (*_t_asn_notify_get_port)(AsyncNotify * notify, long listenid);
typedef ANETAPI void (*_t_asn_notify_allow_clear)(AsyncNotify * notify);
typedef ANETAPI void (*_t_asn_notify_allow_add)(AsyncNotify * notify, const char * ip);
typedef ANETAPI void (*_t_asn_notify_allow_del)(AsyncNotify * notify, const char * ip);
typedef ANETAPI void (*_t_asn_notify_allow_enable)(AsyncNotify * notify, int enable);
typedef ANETAPI void (*_t_asn_notify_sid_add)(AsyncNotify * notify, int sid, const char * ip, int port);
typedef ANETAPI void (*_t_asn_notify_sid_del)(AsyncNotify * notify, int sid);
typedef ANETAPI int (*_t_asn_notify_sid_list)(AsyncNotify * notify, int * sids, int maxsize);
typedef ANETAPI void (*_t_asn_notify_sid_clear)(AsyncNotify * notify);
typedef ANETAPI int (*_t_asn_notify_option)(AsyncNotify * notify, int type, long value);
typedef ANETAPI void (*_t_asn_notify_token)(AsyncNotify * notify, const char * token, int size);
typedef ANETAPI void (*_t_asn_notify_trace)(AsyncNotify * notify, const char * prefix, int STDOUT, int color);
typedef ANETAPI AsyncSock* (*_t_asn_sock_new)(void);
typedef ANETAPI void (*_t_asn_sock_delete)(AsyncSock * sock);
typedef ANETAPI int (*_t_asn_sock_connect)(AsyncSock * sock, const char * ip, int port, int head);
typedef ANETAPI int (*_t_asn_sock_assign)(AsyncSock * sock, int fd, int head);
typedef ANETAPI void (*_t_asn_sock_close)(AsyncSock * sock);
typedef ANETAPI int (*_t_asn_sock_state)(const AsyncSock * sock);
typedef ANETAPI int (*_t_asn_sock_fd)(const AsyncSock * sock);
typedef ANETAPI long (*_t_asn_sock_remain)(const AsyncSock * sock);
typedef ANETAPI long (*_t_asn_sock_send)(AsyncSock * sock, const void * ptr, long size, int mask);
typedef ANETAPI long (*_t_asn_sock_recv)(AsyncSock * sock, void * ptr, int size);
typedef ANETAPI long (*_t_asn_sock_send_vector)(AsyncSock * sock, const void * vecptr [], const long veclen [], int count, int mask);
typedef ANETAPI long (*_t_asn_sock_recv_vector)(AsyncSock * sock, void * vecptr [], const long veclen [], int count);
typedef ANETAPI int (*_t_asn_sock_update)(AsyncSock * sock, int what);
typedef ANETAPI void (*_t_asn_sock_process)(AsyncSock * sock);
typedef ANETAPI void (*_t_asn_sock_rc4_set_skey)(AsyncSock * sock, const unsigned char * key, int keylen);
typedef ANETAPI void (*_t_asn_sock_rc4_set_rkey)(AsyncSock * sock, const unsigned char * key, int keylen);
typedef ANETAPI int (*_t_asn_sock_nodelay)(AsyncSock * sock, int nodelay);
typedef ANETAPI int (*_t_asn_sock_sys_buffer)(AsyncSock * sock, long rcvbuf, long sndbuf);
typedef ANETAPI int (*_t_asn_sock_keepalive)(AsyncSock * sock, int keepcnt, int idle, int intvl);


//======================================================================
// Address Of Interfaces
//======================================================================
ANETAPI AsyncCore* (*_p_asn_core_new)(void) = 0;
ANETAPI void (*_p_asn_core_delete)(AsyncCore * core) = 0;
ANETAPI void (*_p_asn_core_wait)(AsyncCore * core, unsigned long millisec) = 0;
ANETAPI void (*_p_asn_core_notify)(AsyncCore * core) = 0;
ANETAPI long (*_p_asn_core_read)(AsyncCore * core, int * event, long * wparam, long * lparam, void * data, long size) = 0;
ANETAPI long (*_p_asn_core_send)(AsyncCore * core, long hid, const void * ptr, long len) = 0;
ANETAPI int (*_p_asn_core_close)(AsyncCore * core, long hid, int code) = 0;
ANETAPI long (*_p_asn_core_send_vector)(AsyncCore * core, long hid, const void * vecptr [], const long veclen [], int count, int mask) = 0;
ANETAPI long (*_p_asn_core_send_mask)(AsyncCore * core, long hid, const void * ptr, long len, int mask) = 0;
ANETAPI long (*_p_asn_core_new_connect)(AsyncCore * core, const char * ip, int port, int header) = 0;
ANETAPI long (*_p_asn_core_new_listen)(AsyncCore * core, const char * ip, int port, int header) = 0;
ANETAPI long (*_p_asn_core_new_assign)(AsyncCore * core, int fd, int header, int check_estab) = 0;
ANETAPI int (*_p_asn_core_post)(AsyncCore * core, long wparam, long lparam, const char * data, long size) = 0;
ANETAPI int (*_p_asn_core_get_mode)(const AsyncCore * core, long hid) = 0;
ANETAPI long (*_p_asn_core_get_tag)(const AsyncCore * core, long hid) = 0;
ANETAPI void (*_p_asn_core_set_tag)(AsyncCore * core, long hid, long tag) = 0;
ANETAPI long (*_p_asn_core_remain)(const AsyncCore * core, long hid) = 0;
ANETAPI void (*_p_asn_core_limit)(AsyncCore * core, long limited, long maxsize) = 0;
ANETAPI long (*_p_asn_core_node_head)(const AsyncCore * core) = 0;
ANETAPI long (*_p_asn_core_node_next)(const AsyncCore * core, long hid) = 0;
ANETAPI long (*_p_asn_core_node_prev)(const AsyncCore * core, long hid) = 0;
ANETAPI int (*_p_asn_core_option)(AsyncCore * core, long hid, int opt, long value) = 0;
ANETAPI int (*_p_asn_core_status)(AsyncCore * core, long hid, int opt) = 0;
ANETAPI int (*_p_asn_core_rc4_set_skey)(AsyncCore * core, long hid, const unsigned char * key, int keylen) = 0;
ANETAPI int (*_p_asn_core_rc4_set_rkey)(AsyncCore * core, long hid, const unsigned char * key, int keylen) = 0;
ANETAPI void (*_p_asn_core_firewall)(AsyncCore * core, AsyncValidator v, void * user) = 0;
ANETAPI void (*_p_asn_core_timeout)(AsyncCore * core, long seconds) = 0;
ANETAPI int (*_p_asn_core_sockname)(const AsyncCore * core, long hid, char * out) = 0;
ANETAPI int (*_p_asn_core_peername)(const AsyncCore * core, long hid, char * out) = 0;
ANETAPI int (*_p_asn_core_disable)(AsyncCore * core, long hid, int value) = 0;
ANETAPI int (*_p_asn_core_nfds)(const AsyncCore * core) = 0;
ANETAPI AsyncNotify* (*_p_asn_notify_new)(int serverid) = 0;
ANETAPI void (*_p_asn_notify_delete)(AsyncNotify * notify) = 0;
ANETAPI void (*_p_asn_notify_wait)(AsyncNotify * notify, unsigned long millisec) = 0;
ANETAPI void (*_p_asn_notify_wake)(AsyncNotify * notify) = 0;
ANETAPI long (*_p_asn_notify_read)(AsyncNotify * notify, int * event, long * wparam, long * lparam, void * data, long maxsize) = 0;
ANETAPI long (*_p_asn_notify_listen)(AsyncNotify * notify, const char * addr, int port, int flag) = 0;
ANETAPI int (*_p_asn_notify_remove)(AsyncNotify * notify, long listenid, int code) = 0;
ANETAPI void (*_p_asn_notify_change)(AsyncNotify * notify, int new_server_id) = 0;
ANETAPI int (*_p_asn_notify_send)(AsyncNotify * notify, int sid, short cmd, const void * data, long size) = 0;
ANETAPI int (*_p_asn_notify_close)(AsyncNotify * notify, int sid, int mode, int code) = 0;
ANETAPI int (*_p_asn_notify_get_port)(AsyncNotify * notify, long listenid) = 0;
ANETAPI void (*_p_asn_notify_allow_clear)(AsyncNotify * notify) = 0;
ANETAPI void (*_p_asn_notify_allow_add)(AsyncNotify * notify, const char * ip) = 0;
ANETAPI void (*_p_asn_notify_allow_del)(AsyncNotify * notify, const char * ip) = 0;
ANETAPI void (*_p_asn_notify_allow_enable)(AsyncNotify * notify, int enable) = 0;
ANETAPI void (*_p_asn_notify_sid_add)(AsyncNotify * notify, int sid, const char * ip, int port) = 0;
ANETAPI void (*_p_asn_notify_sid_del)(AsyncNotify * notify, int sid) = 0;
ANETAPI int (*_p_asn_notify_sid_list)(AsyncNotify * notify, int * sids, int maxsize) = 0;
ANETAPI void (*_p_asn_notify_sid_clear)(AsyncNotify * notify) = 0;
ANETAPI int (*_p_asn_notify_option)(AsyncNotify * notify, int type, long value) = 0;
ANETAPI void (*_p_asn_notify_token)(AsyncNotify * notify, const char * token, int size) = 0;
ANETAPI void (*_p_asn_notify_trace)(AsyncNotify * notify, const char * prefix, int STDOUT, int color) = 0;
ANETAPI AsyncSock* (*_p_asn_sock_new)(void) = 0;
ANETAPI void (*_p_asn_sock_delete)(AsyncSock * sock) = 0;
ANETAPI int (*_p_asn_sock_connect)(AsyncSock * sock, const char * ip, int port, int head) = 0;
ANETAPI int (*_p_asn_sock_assign)(AsyncSock * sock, int fd, int head) = 0;
ANETAPI void (*_p_asn_sock_close)(AsyncSock * sock) = 0;
ANETAPI int (*_p_asn_sock_state)(const AsyncSock * sock) = 0;
ANETAPI int (*_p_asn_sock_fd)(const AsyncSock * sock) = 0;
ANETAPI long (*_p_asn_sock_remain)(const AsyncSock * sock) = 0;
ANETAPI long (*_p_asn_sock_send)(AsyncSock * sock, const void * ptr, long size, int mask) = 0;
ANETAPI long (*_p_asn_sock_recv)(AsyncSock * sock, void * ptr, int size) = 0;
ANETAPI long (*_p_asn_sock_send_vector)(AsyncSock * sock, const void * vecptr [], const long veclen [], int count, int mask) = 0;
ANETAPI long (*_p_asn_sock_recv_vector)(AsyncSock * sock, void * vecptr [], const long veclen [], int count) = 0;
ANETAPI int (*_p_asn_sock_update)(AsyncSock * sock, int what) = 0;
ANETAPI void (*_p_asn_sock_process)(AsyncSock * sock) = 0;
ANETAPI void (*_p_asn_sock_rc4_set_skey)(AsyncSock * sock, const unsigned char * key, int keylen) = 0;
ANETAPI void (*_p_asn_sock_rc4_set_rkey)(AsyncSock * sock, const unsigned char * key, int keylen) = 0;
ANETAPI int (*_p_asn_sock_nodelay)(AsyncSock * sock, int nodelay) = 0;
ANETAPI int (*_p_asn_sock_sys_buffer)(AsyncSock * sock, long rcvbuf, long sndbuf) = 0;
ANETAPI int (*_p_asn_sock_keepalive)(AsyncSock * sock, int keepcnt, int idle, int intvl) = 0;


//======================================================================
// Internal Definition
//======================================================================
static int AsyncLoader_inited = 0;
static void* AsyncLoader_module = NULL;


//======================================================================
// Initializer: load module, returns zero for success
//======================================================================
int AsyncLoader_Init(const char *dllname)
{
	void *mod = NULL;
	if (AsyncLoader_inited) return 0;
#if defined(WIN32) || defined(WIN64) || defined(_WIN32) || defined(_WIN64)
	mod = (void*)LoadLibraryA(dllname);
#else
	mod = (void*)dlopen(dllname, RTLD_LAZY);
#endif
	if (mod == NULL) return -1;
#if defined(WIN32) || defined(WIN64) || defined(_WIN32) || defined(_WIN64)
	_p_asn_core_new = (_t_asn_core_new)GetProcAddress((HINSTANCE)mod, "asn_core_new");
	_p_asn_core_delete = (_t_asn_core_delete)GetProcAddress((HINSTANCE)mod, "asn_core_delete");
	_p_asn_core_wait = (_t_asn_core_wait)GetProcAddress((HINSTANCE)mod, "asn_core_wait");
	_p_asn_core_notify = (_t_asn_core_notify)GetProcAddress((HINSTANCE)mod, "asn_core_notify");
	_p_asn_core_read = (_t_asn_core_read)GetProcAddress((HINSTANCE)mod, "asn_core_read");
	_p_asn_core_send = (_t_asn_core_send)GetProcAddress((HINSTANCE)mod, "asn_core_send");
	_p_asn_core_close = (_t_asn_core_close)GetProcAddress((HINSTANCE)mod, "asn_core_close");
	_p_asn_core_send_vector = (_t_asn_core_send_vector)GetProcAddress((HINSTANCE)mod, "asn_core_send_vector");
	_p_asn_core_send_mask = (_t_asn_core_send_mask)GetProcAddress((HINSTANCE)mod, "asn_core_send_mask");
	_p_asn_core_new_connect = (_t_asn_core_new_connect)GetProcAddress((HINSTANCE)mod, "asn_core_new_connect");
	_p_asn_core_new_listen = (_t_asn_core_new_listen)GetProcAddress((HINSTANCE)mod, "asn_core_new_listen");
	_p_asn_core_new_assign = (_t_asn_core_new_assign)GetProcAddress((HINSTANCE)mod, "asn_core_new_assign");
	_p_asn_core_post = (_t_asn_core_post)GetProcAddress((HINSTANCE)mod, "asn_core_post");
	_p_asn_core_get_mode = (_t_asn_core_get_mode)GetProcAddress((HINSTANCE)mod, "asn_core_get_mode");
	_p_asn_core_get_tag = (_t_asn_core_get_tag)GetProcAddress((HINSTANCE)mod, "asn_core_get_tag");
	_p_asn_core_set_tag = (_t_asn_core_set_tag)GetProcAddress((HINSTANCE)mod, "asn_core_set_tag");
	_p_asn_core_remain = (_t_asn_core_remain)GetProcAddress((HINSTANCE)mod, "asn_core_remain");
	_p_asn_core_limit = (_t_asn_core_limit)GetProcAddress((HINSTANCE)mod, "asn_core_limit");
	_p_asn_core_node_head = (_t_asn_core_node_head)GetProcAddress((HINSTANCE)mod, "asn_core_node_head");
	_p_asn_core_node_next = (_t_asn_core_node_next)GetProcAddress((HINSTANCE)mod, "asn_core_node_next");
	_p_asn_core_node_prev = (_t_asn_core_node_prev)GetProcAddress((HINSTANCE)mod, "asn_core_node_prev");
	_p_asn_core_option = (_t_asn_core_option)GetProcAddress((HINSTANCE)mod, "asn_core_option");
	_p_asn_core_status = (_t_asn_core_status)GetProcAddress((HINSTANCE)mod, "asn_core_status");
	_p_asn_core_rc4_set_skey = (_t_asn_core_rc4_set_skey)GetProcAddress((HINSTANCE)mod, "asn_core_rc4_set_skey");
	_p_asn_core_rc4_set_rkey = (_t_asn_core_rc4_set_rkey)GetProcAddress((HINSTANCE)mod, "asn_core_rc4_set_rkey");
	_p_asn_core_firewall = (_t_asn_core_firewall)GetProcAddress((HINSTANCE)mod, "asn_core_firewall");
	_p_asn_core_timeout = (_t_asn_core_timeout)GetProcAddress((HINSTANCE)mod, "asn_core_timeout");
	_p_asn_core_sockname = (_t_asn_core_sockname)GetProcAddress((HINSTANCE)mod, "asn_core_sockname");
	_p_asn_core_peername = (_t_asn_core_peername)GetProcAddress((HINSTANCE)mod, "asn_core_peername");
	_p_asn_core_disable = (_t_asn_core_disable)GetProcAddress((HINSTANCE)mod, "asn_core_disable");
	_p_asn_core_nfds = (_t_asn_core_nfds)GetProcAddress((HINSTANCE)mod, "asn_core_nfds");
	_p_asn_notify_new = (_t_asn_notify_new)GetProcAddress((HINSTANCE)mod, "asn_notify_new");
	_p_asn_notify_delete = (_t_asn_notify_delete)GetProcAddress((HINSTANCE)mod, "asn_notify_delete");
	_p_asn_notify_wait = (_t_asn_notify_wait)GetProcAddress((HINSTANCE)mod, "asn_notify_wait");
	_p_asn_notify_wake = (_t_asn_notify_wake)GetProcAddress((HINSTANCE)mod, "asn_notify_wake");
	_p_asn_notify_read = (_t_asn_notify_read)GetProcAddress((HINSTANCE)mod, "asn_notify_read");
	_p_asn_notify_listen = (_t_asn_notify_listen)GetProcAddress((HINSTANCE)mod, "asn_notify_listen");
	_p_asn_notify_remove = (_t_asn_notify_remove)GetProcAddress((HINSTANCE)mod, "asn_notify_remove");
	_p_asn_notify_change = (_t_asn_notify_change)GetProcAddress((HINSTANCE)mod, "asn_notify_change");
	_p_asn_notify_send = (_t_asn_notify_send)GetProcAddress((HINSTANCE)mod, "asn_notify_send");
	_p_asn_notify_close = (_t_asn_notify_close)GetProcAddress((HINSTANCE)mod, "asn_notify_close");
	_p_asn_notify_get_port = (_t_asn_notify_get_port)GetProcAddress((HINSTANCE)mod, "asn_notify_get_port");
	_p_asn_notify_allow_clear = (_t_asn_notify_allow_clear)GetProcAddress((HINSTANCE)mod, "asn_notify_allow_clear");
	_p_asn_notify_allow_add = (_t_asn_notify_allow_add)GetProcAddress((HINSTANCE)mod, "asn_notify_allow_add");
	_p_asn_notify_allow_del = (_t_asn_notify_allow_del)GetProcAddress((HINSTANCE)mod, "asn_notify_allow_del");
	_p_asn_notify_allow_enable = (_t_asn_notify_allow_enable)GetProcAddress((HINSTANCE)mod, "asn_notify_allow_enable");
	_p_asn_notify_sid_add = (_t_asn_notify_sid_add)GetProcAddress((HINSTANCE)mod, "asn_notify_sid_add");
	_p_asn_notify_sid_del = (_t_asn_notify_sid_del)GetProcAddress((HINSTANCE)mod, "asn_notify_sid_del");
	_p_asn_notify_sid_list = (_t_asn_notify_sid_list)GetProcAddress((HINSTANCE)mod, "asn_notify_sid_list");
	_p_asn_notify_sid_clear = (_t_asn_notify_sid_clear)GetProcAddress((HINSTANCE)mod, "asn_notify_sid_clear");
	_p_asn_notify_option = (_t_asn_notify_option)GetProcAddress((HINSTANCE)mod, "asn_notify_option");
	_p_asn_notify_token = (_t_asn_notify_token)GetProcAddress((HINSTANCE)mod, "asn_notify_token");
	_p_asn_notify_trace = (_t_asn_notify_trace)GetProcAddress((HINSTANCE)mod, "asn_notify_trace");
	_p_asn_sock_new = (_t_asn_sock_new)GetProcAddress((HINSTANCE)mod, "asn_sock_new");
	_p_asn_sock_delete = (_t_asn_sock_delete)GetProcAddress((HINSTANCE)mod, "asn_sock_delete");
	_p_asn_sock_connect = (_t_asn_sock_connect)GetProcAddress((HINSTANCE)mod, "asn_sock_connect");
	_p_asn_sock_assign = (_t_asn_sock_assign)GetProcAddress((HINSTANCE)mod, "asn_sock_assign");
	_p_asn_sock_close = (_t_asn_sock_close)GetProcAddress((HINSTANCE)mod, "asn_sock_close");
	_p_asn_sock_state = (_t_asn_sock_state)GetProcAddress((HINSTANCE)mod, "asn_sock_state");
	_p_asn_sock_fd = (_t_asn_sock_fd)GetProcAddress((HINSTANCE)mod, "asn_sock_fd");
	_p_asn_sock_remain = (_t_asn_sock_remain)GetProcAddress((HINSTANCE)mod, "asn_sock_remain");
	_p_asn_sock_send = (_t_asn_sock_send)GetProcAddress((HINSTANCE)mod, "asn_sock_send");
	_p_asn_sock_recv = (_t_asn_sock_recv)GetProcAddress((HINSTANCE)mod, "asn_sock_recv");
	_p_asn_sock_send_vector = (_t_asn_sock_send_vector)GetProcAddress((HINSTANCE)mod, "asn_sock_send_vector");
	_p_asn_sock_recv_vector = (_t_asn_sock_recv_vector)GetProcAddress((HINSTANCE)mod, "asn_sock_recv_vector");
	_p_asn_sock_update = (_t_asn_sock_update)GetProcAddress((HINSTANCE)mod, "asn_sock_update");
	_p_asn_sock_process = (_t_asn_sock_process)GetProcAddress((HINSTANCE)mod, "asn_sock_process");
	_p_asn_sock_rc4_set_skey = (_t_asn_sock_rc4_set_skey)GetProcAddress((HINSTANCE)mod, "asn_sock_rc4_set_skey");
	_p_asn_sock_rc4_set_rkey = (_t_asn_sock_rc4_set_rkey)GetProcAddress((HINSTANCE)mod, "asn_sock_rc4_set_rkey");
	_p_asn_sock_nodelay = (_t_asn_sock_nodelay)GetProcAddress((HINSTANCE)mod, "asn_sock_nodelay");
	_p_asn_sock_sys_buffer = (_t_asn_sock_sys_buffer)GetProcAddress((HINSTANCE)mod, "asn_sock_sys_buffer");
	_p_asn_sock_keepalive = (_t_asn_sock_keepalive)GetProcAddress((HINSTANCE)mod, "asn_sock_keepalive");
#else
	_p_asn_core_new = (_t_asn_core_new)dlsym(mod, "asn_core_new");
	_p_asn_core_delete = (_t_asn_core_delete)dlsym(mod, "asn_core_delete");
	_p_asn_core_wait = (_t_asn_core_wait)dlsym(mod, "asn_core_wait");
	_p_asn_core_notify = (_t_asn_core_notify)dlsym(mod, "asn_core_notify");
	_p_asn_core_read = (_t_asn_core_read)dlsym(mod, "asn_core_read");
	_p_asn_core_send = (_t_asn_core_send)dlsym(mod, "asn_core_send");
	_p_asn_core_close = (_t_asn_core_close)dlsym(mod, "asn_core_close");
	_p_asn_core_send_vector = (_t_asn_core_send_vector)dlsym(mod, "asn_core_send_vector");
	_p_asn_core_send_mask = (_t_asn_core_send_mask)dlsym(mod, "asn_core_send_mask");
	_p_asn_core_new_connect = (_t_asn_core_new_connect)dlsym(mod, "asn_core_new_connect");
	_p_asn_core_new_listen = (_t_asn_core_new_listen)dlsym(mod, "asn_core_new_listen");
	_p_asn_core_new_assign = (_t_asn_core_new_assign)dlsym(mod, "asn_core_new_assign");
	_p_asn_core_post = (_t_asn_core_post)dlsym(mod, "asn_core_post");
	_p_asn_core_get_mode = (_t_asn_core_get_mode)dlsym(mod, "asn_core_get_mode");
	_p_asn_core_get_tag = (_t_asn_core_get_tag)dlsym(mod, "asn_core_get_tag");
	_p_asn_core_set_tag = (_t_asn_core_set_tag)dlsym(mod, "asn_core_set_tag");
	_p_asn_core_remain = (_t_asn_core_remain)dlsym(mod, "asn_core_remain");
	_p_asn_core_limit = (_t_asn_core_limit)dlsym(mod, "asn_core_limit");
	_p_asn_core_node_head = (_t_asn_core_node_head)dlsym(mod, "asn_core_node_head");
	_p_asn_core_node_next = (_t_asn_core_node_next)dlsym(mod, "asn_core_node_next");
	_p_asn_core_node_prev = (_t_asn_core_node_prev)dlsym(mod, "asn_core_node_prev");
	_p_asn_core_option = (_t_asn_core_option)dlsym(mod, "asn_core_option");
	_p_asn_core_status = (_t_asn_core_status)dlsym(mod, "asn_core_status");
	_p_asn_core_rc4_set_skey = (_t_asn_core_rc4_set_skey)dlsym(mod, "asn_core_rc4_set_skey");
	_p_asn_core_rc4_set_rkey = (_t_asn_core_rc4_set_rkey)dlsym(mod, "asn_core_rc4_set_rkey");
	_p_asn_core_firewall = (_t_asn_core_firewall)dlsym(mod, "asn_core_firewall");
	_p_asn_core_timeout = (_t_asn_core_timeout)dlsym(mod, "asn_core_timeout");
	_p_asn_core_sockname = (_t_asn_core_sockname)dlsym(mod, "asn_core_sockname");
	_p_asn_core_peername = (_t_asn_core_peername)dlsym(mod, "asn_core_peername");
	_p_asn_core_disable = (_t_asn_core_disable)dlsym(mod, "asn_core_disable");
	_p_asn_core_nfds = (_t_asn_core_nfds)dlsym(mod, "asn_core_nfds");
	_p_asn_notify_new = (_t_asn_notify_new)dlsym(mod, "asn_notify_new");
	_p_asn_notify_delete = (_t_asn_notify_delete)dlsym(mod, "asn_notify_delete");
	_p_asn_notify_wait = (_t_asn_notify_wait)dlsym(mod, "asn_notify_wait");
	_p_asn_notify_wake = (_t_asn_notify_wake)dlsym(mod, "asn_notify_wake");
	_p_asn_notify_read = (_t_asn_notify_read)dlsym(mod, "asn_notify_read");
	_p_asn_notify_listen = (_t_asn_notify_listen)dlsym(mod, "asn_notify_listen");
	_p_asn_notify_remove = (_t_asn_notify_remove)dlsym(mod, "asn_notify_remove");
	_p_asn_notify_change = (_t_asn_notify_change)dlsym(mod, "asn_notify_change");
	_p_asn_notify_send = (_t_asn_notify_send)dlsym(mod, "asn_notify_send");
	_p_asn_notify_close = (_t_asn_notify_close)dlsym(mod, "asn_notify_close");
	_p_asn_notify_get_port = (_t_asn_notify_get_port)dlsym(mod, "asn_notify_get_port");
	_p_asn_notify_allow_clear = (_t_asn_notify_allow_clear)dlsym(mod, "asn_notify_allow_clear");
	_p_asn_notify_allow_add = (_t_asn_notify_allow_add)dlsym(mod, "asn_notify_allow_add");
	_p_asn_notify_allow_del = (_t_asn_notify_allow_del)dlsym(mod, "asn_notify_allow_del");
	_p_asn_notify_allow_enable = (_t_asn_notify_allow_enable)dlsym(mod, "asn_notify_allow_enable");
	_p_asn_notify_sid_add = (_t_asn_notify_sid_add)dlsym(mod, "asn_notify_sid_add");
	_p_asn_notify_sid_del = (_t_asn_notify_sid_del)dlsym(mod, "asn_notify_sid_del");
	_p_asn_notify_sid_list = (_t_asn_notify_sid_list)dlsym(mod, "asn_notify_sid_list");
	_p_asn_notify_sid_clear = (_t_asn_notify_sid_clear)dlsym(mod, "asn_notify_sid_clear");
	_p_asn_notify_option = (_t_asn_notify_option)dlsym(mod, "asn_notify_option");
	_p_asn_notify_token = (_t_asn_notify_token)dlsym(mod, "asn_notify_token");
	_p_asn_notify_trace = (_t_asn_notify_trace)dlsym(mod, "asn_notify_trace");
	_p_asn_sock_new = (_t_asn_sock_new)dlsym(mod, "asn_sock_new");
	_p_asn_sock_delete = (_t_asn_sock_delete)dlsym(mod, "asn_sock_delete");
	_p_asn_sock_connect = (_t_asn_sock_connect)dlsym(mod, "asn_sock_connect");
	_p_asn_sock_assign = (_t_asn_sock_assign)dlsym(mod, "asn_sock_assign");
	_p_asn_sock_close = (_t_asn_sock_close)dlsym(mod, "asn_sock_close");
	_p_asn_sock_state = (_t_asn_sock_state)dlsym(mod, "asn_sock_state");
	_p_asn_sock_fd = (_t_asn_sock_fd)dlsym(mod, "asn_sock_fd");
	_p_asn_sock_remain = (_t_asn_sock_remain)dlsym(mod, "asn_sock_remain");
	_p_asn_sock_send = (_t_asn_sock_send)dlsym(mod, "asn_sock_send");
	_p_asn_sock_recv = (_t_asn_sock_recv)dlsym(mod, "asn_sock_recv");
	_p_asn_sock_send_vector = (_t_asn_sock_send_vector)dlsym(mod, "asn_sock_send_vector");
	_p_asn_sock_recv_vector = (_t_asn_sock_recv_vector)dlsym(mod, "asn_sock_recv_vector");
	_p_asn_sock_update = (_t_asn_sock_update)dlsym(mod, "asn_sock_update");
	_p_asn_sock_process = (_t_asn_sock_process)dlsym(mod, "asn_sock_process");
	_p_asn_sock_rc4_set_skey = (_t_asn_sock_rc4_set_skey)dlsym(mod, "asn_sock_rc4_set_skey");
	_p_asn_sock_rc4_set_rkey = (_t_asn_sock_rc4_set_rkey)dlsym(mod, "asn_sock_rc4_set_rkey");
	_p_asn_sock_nodelay = (_t_asn_sock_nodelay)dlsym(mod, "asn_sock_nodelay");
	_p_asn_sock_sys_buffer = (_t_asn_sock_sys_buffer)dlsym(mod, "asn_sock_sys_buffer");
	_p_asn_sock_keepalive = (_t_asn_sock_keepalive)dlsym(mod, "asn_sock_keepalive");
#endif
	if (_p_asn_core_new == 0) return 1;
	if (_p_asn_core_delete == 0) return 2;
	if (_p_asn_core_wait == 0) return 3;
	if (_p_asn_core_notify == 0) return 4;
	if (_p_asn_core_read == 0) return 5;
	if (_p_asn_core_send == 0) return 6;
	if (_p_asn_core_close == 0) return 7;
	if (_p_asn_core_send_vector == 0) return 8;
	if (_p_asn_core_send_mask == 0) return 9;
	if (_p_asn_core_new_connect == 0) return 10;
	if (_p_asn_core_new_listen == 0) return 11;
	if (_p_asn_core_new_assign == 0) return 12;
	if (_p_asn_core_post == 0) return 13;
	if (_p_asn_core_get_mode == 0) return 14;
	if (_p_asn_core_get_tag == 0) return 15;
	if (_p_asn_core_set_tag == 0) return 16;
	if (_p_asn_core_remain == 0) return 17;
	if (_p_asn_core_limit == 0) return 18;
	if (_p_asn_core_node_head == 0) return 19;
	if (_p_asn_core_node_next == 0) return 20;
	if (_p_asn_core_node_prev == 0) return 21;
	if (_p_asn_core_option == 0) return 22;
	if (_p_asn_core_status == 0) return 23;
	if (_p_asn_core_rc4_set_skey == 0) return 24;
	if (_p_asn_core_rc4_set_rkey == 0) return 25;
	if (_p_asn_core_firewall == 0) return 26;
	if (_p_asn_core_timeout == 0) return 27;
	if (_p_asn_core_sockname == 0) return 28;
	if (_p_asn_core_peername == 0) return 29;
	if (_p_asn_core_disable == 0) return 30;
	if (_p_asn_core_nfds == 0) return 31;
	if (_p_asn_notify_new == 0) return 32;
	if (_p_asn_notify_delete == 0) return 33;
	if (_p_asn_notify_wait == 0) return 34;
	if (_p_asn_notify_wake == 0) return 35;
	if (_p_asn_notify_read == 0) return 36;
	if (_p_asn_notify_listen == 0) return 37;
	if (_p_asn_notify_remove == 0) return 38;
	if (_p_asn_notify_change == 0) return 39;
	if (_p_asn_notify_send == 0) return 40;
	if (_p_asn_notify_close == 0) return 41;
	if (_p_asn_notify_get_port == 0) return 42;
	if (_p_asn_notify_allow_clear == 0) return 43;
	if (_p_asn_notify_allow_add == 0) return 44;
	if (_p_asn_notify_allow_del == 0) return 45;
	if (_p_asn_notify_allow_enable == 0) return 46;
	if (_p_asn_notify_sid_add == 0) return 47;
	if (_p_asn_notify_sid_del == 0) return 48;
	if (_p_asn_notify_sid_list == 0) return 49;
	if (_p_asn_notify_sid_clear == 0) return 50;
	if (_p_asn_notify_option == 0) return 51;
	if (_p_asn_notify_token == 0) return 52;
	if (_p_asn_notify_trace == 0) return 53;
	if (_p_asn_sock_new == 0) return 54;
	if (_p_asn_sock_delete == 0) return 55;
	if (_p_asn_sock_connect == 0) return 56;
	if (_p_asn_sock_assign == 0) return 57;
	if (_p_asn_sock_close == 0) return 58;
	if (_p_asn_sock_state == 0) return 59;
	if (_p_asn_sock_fd == 0) return 60;
	if (_p_asn_sock_remain == 0) return 61;
	if (_p_asn_sock_send == 0) return 62;
	if (_p_asn_sock_recv == 0) return 63;
	if (_p_asn_sock_send_vector == 0) return 64;
	if (_p_asn_sock_recv_vector == 0) return 65;
	if (_p_asn_sock_update == 0) return 66;
	if (_p_asn_sock_process == 0) return 67;
	if (_p_asn_sock_rc4_set_skey == 0) return 68;
	if (_p_asn_sock_rc4_set_rkey == 0) return 69;
	if (_p_asn_sock_nodelay == 0) return 70;
	if (_p_asn_sock_sys_buffer == 0) return 71;
	if (_p_asn_sock_keepalive == 0) return 72;
	AsyncLoader_module = mod;
	AsyncLoader_inited = 1;
	return 0;
}


//======================================================================
// Quit: Unload dynamic module
//======================================================================
void AsyncLoader_Quit(void)
{
	void *mod = AsyncLoader_module;
	AsyncLoader_inited = 0;
	AsyncLoader_module = NULL;
	_p_asn_core_new = 0;
	_p_asn_core_delete = 0;
	_p_asn_core_wait = 0;
	_p_asn_core_notify = 0;
	_p_asn_core_read = 0;
	_p_asn_core_send = 0;
	_p_asn_core_close = 0;
	_p_asn_core_send_vector = 0;
	_p_asn_core_send_mask = 0;
	_p_asn_core_new_connect = 0;
	_p_asn_core_new_listen = 0;
	_p_asn_core_new_assign = 0;
	_p_asn_core_post = 0;
	_p_asn_core_get_mode = 0;
	_p_asn_core_get_tag = 0;
	_p_asn_core_set_tag = 0;
	_p_asn_core_remain = 0;
	_p_asn_core_limit = 0;
	_p_asn_core_node_head = 0;
	_p_asn_core_node_next = 0;
	_p_asn_core_node_prev = 0;
	_p_asn_core_option = 0;
	_p_asn_core_status = 0;
	_p_asn_core_rc4_set_skey = 0;
	_p_asn_core_rc4_set_rkey = 0;
	_p_asn_core_firewall = 0;
	_p_asn_core_timeout = 0;
	_p_asn_core_sockname = 0;
	_p_asn_core_peername = 0;
	_p_asn_core_disable = 0;
	_p_asn_core_nfds = 0;
	_p_asn_notify_new = 0;
	_p_asn_notify_delete = 0;
	_p_asn_notify_wait = 0;
	_p_asn_notify_wake = 0;
	_p_asn_notify_read = 0;
	_p_asn_notify_listen = 0;
	_p_asn_notify_remove = 0;
	_p_asn_notify_change = 0;
	_p_asn_notify_send = 0;
	_p_asn_notify_close = 0;
	_p_asn_notify_get_port = 0;
	_p_asn_notify_allow_clear = 0;
	_p_asn_notify_allow_add = 0;
	_p_asn_notify_allow_del = 0;
	_p_asn_notify_allow_enable = 0;
	_p_asn_notify_sid_add = 0;
	_p_asn_notify_sid_del = 0;
	_p_asn_notify_sid_list = 0;
	_p_asn_notify_sid_clear = 0;
	_p_asn_notify_option = 0;
	_p_asn_notify_token = 0;
	_p_asn_notify_trace = 0;
	_p_asn_sock_new = 0;
	_p_asn_sock_delete = 0;
	_p_asn_sock_connect = 0;
	_p_asn_sock_assign = 0;
	_p_asn_sock_close = 0;
	_p_asn_sock_state = 0;
	_p_asn_sock_fd = 0;
	_p_asn_sock_remain = 0;
	_p_asn_sock_send = 0;
	_p_asn_sock_recv = 0;
	_p_asn_sock_send_vector = 0;
	_p_asn_sock_recv_vector = 0;
	_p_asn_sock_update = 0;
	_p_asn_sock_process = 0;
	_p_asn_sock_rc4_set_skey = 0;
	_p_asn_sock_rc4_set_rkey = 0;
	_p_asn_sock_nodelay = 0;
	_p_asn_sock_sys_buffer = 0;
	_p_asn_sock_keepalive = 0;
	if (mod != NULL) {
#if defined(WIN32) || defined(WIN64) || defined(_WIN32) || defined(_WIN64)
		FreeLibrary((HINSTANCE)mod);
#else
		dlclose(mod);
#endif
	}
}


//----------------------------------------------------------------------
// export: asn_core_new
//----------------------------------------------------------------------
ANETAPI AsyncCore* asn_core_new(void) {
	return _p_asn_core_new();
}

//----------------------------------------------------------------------
// export: asn_core_delete
//----------------------------------------------------------------------
ANETAPI void asn_core_delete(AsyncCore * core) {
	_p_asn_core_delete(core);
}

//----------------------------------------------------------------------
// export: asn_core_wait
//----------------------------------------------------------------------
ANETAPI void asn_core_wait(AsyncCore * core, unsigned long millisec) {
	_p_asn_core_wait(core, millisec);
}

//----------------------------------------------------------------------
// export: asn_core_notify
//----------------------------------------------------------------------
ANETAPI void asn_core_notify(AsyncCore * core) {
	_p_asn_core_notify(core);
}

//----------------------------------------------------------------------
// export: asn_core_read
//----------------------------------------------------------------------
ANETAPI long asn_core_read(AsyncCore * core, int * event, long * wparam, long * lparam, void * data, long size) {
	return _p_asn_core_read(core, event, wparam, lparam, data, size);
}

//----------------------------------------------------------------------
// export: asn_core_send
//----------------------------------------------------------------------
ANETAPI long asn_core_send(AsyncCore * core, long hid, const void * ptr, long len) {
	return _p_asn_core_send(core, hid, ptr, len);
}

//----------------------------------------------------------------------
// export: asn_core_close
//----------------------------------------------------------------------
ANETAPI int asn_core_close(AsyncCore * core, long hid, int code) {
	return _p_asn_core_close(core, hid, code);
}

//----------------------------------------------------------------------
// export: asn_core_send_vector
//----------------------------------------------------------------------
ANETAPI long asn_core_send_vector(AsyncCore * core, long hid, const void * vecptr [], const long veclen [], int count, int mask) {
	return _p_asn_core_send_vector(core, hid, vecptr, veclen, count, mask);
}

//----------------------------------------------------------------------
// export: asn_core_send_mask
//----------------------------------------------------------------------
ANETAPI long asn_core_send_mask(AsyncCore * core, long hid, const void * ptr, long len, int mask) {
	return _p_asn_core_send_mask(core, hid, ptr, len, mask);
}

//----------------------------------------------------------------------
// export: asn_core_new_connect
//----------------------------------------------------------------------
ANETAPI long asn_core_new_connect(AsyncCore * core, const char * ip, int port, int header) {
	return _p_asn_core_new_connect(core, ip, port, header);
}

//----------------------------------------------------------------------
// export: asn_core_new_listen
//----------------------------------------------------------------------
ANETAPI long asn_core_new_listen(AsyncCore * core, const char * ip, int port, int header) {
	return _p_asn_core_new_listen(core, ip, port, header);
}

//----------------------------------------------------------------------
// export: asn_core_new_assign
//----------------------------------------------------------------------
ANETAPI long asn_core_new_assign(AsyncCore * core, int fd, int header, int check_estab) {
	return _p_asn_core_new_assign(core, fd, header, check_estab);
}

//----------------------------------------------------------------------
// export: asn_core_post
//----------------------------------------------------------------------
ANETAPI int asn_core_post(AsyncCore * core, long wparam, long lparam, const char * data, long size) {
	return _p_asn_core_post(core, wparam, lparam, data, size);
}

//----------------------------------------------------------------------
// export: asn_core_get_mode
//----------------------------------------------------------------------
ANETAPI int asn_core_get_mode(const AsyncCore * core, long hid) {
	return _p_asn_core_get_mode(core, hid);
}

//----------------------------------------------------------------------
// export: asn_core_get_tag
//----------------------------------------------------------------------
ANETAPI long asn_core_get_tag(const AsyncCore * core, long hid) {
	return _p_asn_core_get_tag(core, hid);
}

//----------------------------------------------------------------------
// export: asn_core_set_tag
//----------------------------------------------------------------------
ANETAPI void asn_core_set_tag(AsyncCore * core, long hid, long tag) {
	_p_asn_core_set_tag(core, hid, tag);
}

//----------------------------------------------------------------------
// export: asn_core_remain
//----------------------------------------------------------------------
ANETAPI long asn_core_remain(const AsyncCore * core, long hid) {
	return _p_asn_core_remain(core, hid);
}

//----------------------------------------------------------------------
// export: asn_core_limit
//----------------------------------------------------------------------
ANETAPI void asn_core_limit(AsyncCore * core, long limited, long maxsize) {
	_p_asn_core_limit(core, limited, maxsize);
}

//----------------------------------------------------------------------
// export: asn_core_node_head
//----------------------------------------------------------------------
ANETAPI long asn_core_node_head(const AsyncCore * core) {
	return _p_asn_core_node_head(core);
}

//----------------------------------------------------------------------
// export: asn_core_node_next
//----------------------------------------------------------------------
ANETAPI long asn_core_node_next(const AsyncCore * core, long hid) {
	return _p_asn_core_node_next(core, hid);
}

//----------------------------------------------------------------------
// export: asn_core_node_prev
//----------------------------------------------------------------------
ANETAPI long asn_core_node_prev(const AsyncCore * core, long hid) {
	return _p_asn_core_node_prev(core, hid);
}

//----------------------------------------------------------------------
// export: asn_core_option
//----------------------------------------------------------------------
ANETAPI int asn_core_option(AsyncCore * core, long hid, int opt, long value) {
	return _p_asn_core_option(core, hid, opt, value);
}

//----------------------------------------------------------------------
// export: asn_core_status
//----------------------------------------------------------------------
ANETAPI int asn_core_status(AsyncCore * core, long hid, int opt) {
	return _p_asn_core_status(core, hid, opt);
}

//----------------------------------------------------------------------
// export: asn_core_rc4_set_skey
//----------------------------------------------------------------------
ANETAPI int asn_core_rc4_set_skey(AsyncCore * core, long hid, const unsigned char * key, int keylen) {
	return _p_asn_core_rc4_set_skey(core, hid, key, keylen);
}

//----------------------------------------------------------------------
// export: asn_core_rc4_set_rkey
//----------------------------------------------------------------------
ANETAPI int asn_core_rc4_set_rkey(AsyncCore * core, long hid, const unsigned char * key, int keylen) {
	return _p_asn_core_rc4_set_rkey(core, hid, key, keylen);
}

//----------------------------------------------------------------------
// export: asn_core_firewall
//----------------------------------------------------------------------
ANETAPI void asn_core_firewall(AsyncCore * core, AsyncValidator v, void * user) {
	_p_asn_core_firewall(core, v, user);
}

//----------------------------------------------------------------------
// export: asn_core_timeout
//----------------------------------------------------------------------
ANETAPI void asn_core_timeout(AsyncCore * core, long seconds) {
	_p_asn_core_timeout(core, seconds);
}

//----------------------------------------------------------------------
// export: asn_core_sockname
//----------------------------------------------------------------------
ANETAPI int asn_core_sockname(const AsyncCore * core, long hid, char * out) {
	return _p_asn_core_sockname(core, hid, out);
}

//----------------------------------------------------------------------
// export: asn_core_peername
//----------------------------------------------------------------------
ANETAPI int asn_core_peername(const AsyncCore * core, long hid, char * out) {
	return _p_asn_core_peername(core, hid, out);
}

//----------------------------------------------------------------------
// export: asn_core_disable
//----------------------------------------------------------------------
ANETAPI int asn_core_disable(AsyncCore * core, long hid, int value) {
	return _p_asn_core_disable(core, hid, value);
}

//----------------------------------------------------------------------
// export: asn_core_nfds
//----------------------------------------------------------------------
ANETAPI int asn_core_nfds(const AsyncCore * core) {
	return _p_asn_core_nfds(core);
}

//----------------------------------------------------------------------
// export: asn_notify_new
//----------------------------------------------------------------------
ANETAPI AsyncNotify* asn_notify_new(int serverid) {
	return _p_asn_notify_new(serverid);
}

//----------------------------------------------------------------------
// export: asn_notify_delete
//----------------------------------------------------------------------
ANETAPI void asn_notify_delete(AsyncNotify * notify) {
	_p_asn_notify_delete(notify);
}

//----------------------------------------------------------------------
// export: asn_notify_wait
//----------------------------------------------------------------------
ANETAPI void asn_notify_wait(AsyncNotify * notify, unsigned long millisec) {
	_p_asn_notify_wait(notify, millisec);
}

//----------------------------------------------------------------------
// export: asn_notify_wake
//----------------------------------------------------------------------
ANETAPI void asn_notify_wake(AsyncNotify * notify) {
	_p_asn_notify_wake(notify);
}

//----------------------------------------------------------------------
// export: asn_notify_read
//----------------------------------------------------------------------
ANETAPI long asn_notify_read(AsyncNotify * notify, int * event, long * wparam, long * lparam, void * data, long maxsize) {
	return _p_asn_notify_read(notify, event, wparam, lparam, data, maxsize);
}

//----------------------------------------------------------------------
// export: asn_notify_listen
//----------------------------------------------------------------------
ANETAPI long asn_notify_listen(AsyncNotify * notify, const char * addr, int port, int flag) {
	return _p_asn_notify_listen(notify, addr, port, flag);
}

//----------------------------------------------------------------------
// export: asn_notify_remove
//----------------------------------------------------------------------
ANETAPI int asn_notify_remove(AsyncNotify * notify, long listenid, int code) {
	return _p_asn_notify_remove(notify, listenid, code);
}

//----------------------------------------------------------------------
// export: asn_notify_change
//----------------------------------------------------------------------
ANETAPI void asn_notify_change(AsyncNotify * notify, int new_server_id) {
	_p_asn_notify_change(notify, new_server_id);
}

//----------------------------------------------------------------------
// export: asn_notify_send
//----------------------------------------------------------------------
ANETAPI int asn_notify_send(AsyncNotify * notify, int sid, short cmd, const void * data, long size) {
	return _p_asn_notify_send(notify, sid, cmd, data, size);
}

//----------------------------------------------------------------------
// export: asn_notify_close
//----------------------------------------------------------------------
ANETAPI int asn_notify_close(AsyncNotify * notify, int sid, int mode, int code) {
	return _p_asn_notify_close(notify, sid, mode, code);
}

//----------------------------------------------------------------------
// export: asn_notify_get_port
//----------------------------------------------------------------------
ANETAPI int asn_notify_get_port(AsyncNotify * notify, long listenid) {
	return _p_asn_notify_get_port(notify, listenid);
}

//----------------------------------------------------------------------
// export: asn_notify_allow_clear
//----------------------------------------------------------------------
ANETAPI void asn_notify_allow_clear(AsyncNotify * notify) {
	_p_asn_notify_allow_clear(notify);
}

//----------------------------------------------------------------------
// export: asn_notify_allow_add
//----------------------------------------------------------------------
ANETAPI void asn_notify_allow_add(AsyncNotify * notify, const char * ip) {
	_p_asn_notify_allow_add(notify, ip);
}

//----------------------------------------------------------------------
// export: asn_notify_allow_del
//----------------------------------------------------------------------
ANETAPI void asn_notify_allow_del(AsyncNotify * notify, const char * ip) {
	_p_asn_notify_allow_del(notify, ip);
}

//----------------------------------------------------------------------
// export: asn_notify_allow_enable
//----------------------------------------------------------------------
ANETAPI void asn_notify_allow_enable(AsyncNotify * notify, int enable) {
	_p_asn_notify_allow_enable(notify, enable);
}

//----------------------------------------------------------------------
// export: asn_notify_sid_add
//----------------------------------------------------------------------
ANETAPI void asn_notify_sid_add(AsyncNotify * notify, int sid, const char * ip, int port) {
	_p_asn_notify_sid_add(notify, sid, ip, port);
}

//----------------------------------------------------------------------
// export: asn_notify_sid_del
//----------------------------------------------------------------------
ANETAPI void asn_notify_sid_del(AsyncNotify * notify, int sid) {
	_p_asn_notify_sid_del(notify, sid);
}

//----------------------------------------------------------------------
// export: asn_notify_sid_list
//----------------------------------------------------------------------
ANETAPI int asn_notify_sid_list(AsyncNotify * notify, int * sids, int maxsize) {
	return _p_asn_notify_sid_list(notify, sids, maxsize);
}

//----------------------------------------------------------------------
// export: asn_notify_sid_clear
//----------------------------------------------------------------------
ANETAPI void asn_notify_sid_clear(AsyncNotify * notify) {
	_p_asn_notify_sid_clear(notify);
}

//----------------------------------------------------------------------
// export: asn_notify_option
//----------------------------------------------------------------------
ANETAPI int asn_notify_option(AsyncNotify * notify, int type, long value) {
	return _p_asn_notify_option(notify, type, value);
}

//----------------------------------------------------------------------
// export: asn_notify_token
//----------------------------------------------------------------------
ANETAPI void asn_notify_token(AsyncNotify * notify, const char * token, int size) {
	_p_asn_notify_token(notify, token, size);
}

//----------------------------------------------------------------------
// export: asn_notify_trace
//----------------------------------------------------------------------
ANETAPI void asn_notify_trace(AsyncNotify * notify, const char * prefix, int STDOUT, int color) {
	_p_asn_notify_trace(notify, prefix, STDOUT, color);
}

//----------------------------------------------------------------------
// export: asn_sock_new
//----------------------------------------------------------------------
ANETAPI AsyncSock* asn_sock_new(void) {
	return _p_asn_sock_new();
}

//----------------------------------------------------------------------
// export: asn_sock_delete
//----------------------------------------------------------------------
ANETAPI void asn_sock_delete(AsyncSock * sock) {
	_p_asn_sock_delete(sock);
}

//----------------------------------------------------------------------
// export: asn_sock_connect
//----------------------------------------------------------------------
ANETAPI int asn_sock_connect(AsyncSock * sock, const char * ip, int port, int head) {
	return _p_asn_sock_connect(sock, ip, port, head);
}

//----------------------------------------------------------------------
// export: asn_sock_assign
//----------------------------------------------------------------------
ANETAPI int asn_sock_assign(AsyncSock * sock, int fd, int head) {
	return _p_asn_sock_assign(sock, fd, head);
}

//----------------------------------------------------------------------
// export: asn_sock_close
//----------------------------------------------------------------------
ANETAPI void asn_sock_close(AsyncSock * sock) {
	_p_asn_sock_close(sock);
}

//----------------------------------------------------------------------
// export: asn_sock_state
//----------------------------------------------------------------------
ANETAPI int asn_sock_state(const AsyncSock * sock) {
	return _p_asn_sock_state(sock);
}

//----------------------------------------------------------------------
// export: asn_sock_fd
//----------------------------------------------------------------------
ANETAPI int asn_sock_fd(const AsyncSock * sock) {
	return _p_asn_sock_fd(sock);
}

//----------------------------------------------------------------------
// export: asn_sock_remain
//----------------------------------------------------------------------
ANETAPI long asn_sock_remain(const AsyncSock * sock) {
	return _p_asn_sock_remain(sock);
}

//----------------------------------------------------------------------
// export: asn_sock_send
//----------------------------------------------------------------------
ANETAPI long asn_sock_send(AsyncSock * sock, const void * ptr, long size, int mask) {
	return _p_asn_sock_send(sock, ptr, size, mask);
}

//----------------------------------------------------------------------
// export: asn_sock_recv
//----------------------------------------------------------------------
ANETAPI long asn_sock_recv(AsyncSock * sock, void * ptr, int size) {
	return _p_asn_sock_recv(sock, ptr, size);
}

//----------------------------------------------------------------------
// export: asn_sock_send_vector
//----------------------------------------------------------------------
ANETAPI long asn_sock_send_vector(AsyncSock * sock, const void * vecptr [], const long veclen [], int count, int mask) {
	return _p_asn_sock_send_vector(sock, vecptr, veclen, count, mask);
}

//----------------------------------------------------------------------
// export: asn_sock_recv_vector
//----------------------------------------------------------------------
ANETAPI long asn_sock_recv_vector(AsyncSock * sock, void * vecptr [], const long veclen [], int count) {
	return _p_asn_sock_recv_vector(sock, vecptr, veclen, count);
}

//----------------------------------------------------------------------
// export: asn_sock_update
//----------------------------------------------------------------------
ANETAPI int asn_sock_update(AsyncSock * sock, int what) {
	return _p_asn_sock_update(sock, what);
}

//----------------------------------------------------------------------
// export: asn_sock_process
//----------------------------------------------------------------------
ANETAPI void asn_sock_process(AsyncSock * sock) {
	_p_asn_sock_process(sock);
}

//----------------------------------------------------------------------
// export: asn_sock_rc4_set_skey
//----------------------------------------------------------------------
ANETAPI void asn_sock_rc4_set_skey(AsyncSock * sock, const unsigned char * key, int keylen) {
	_p_asn_sock_rc4_set_skey(sock, key, keylen);
}

//----------------------------------------------------------------------
// export: asn_sock_rc4_set_rkey
//----------------------------------------------------------------------
ANETAPI void asn_sock_rc4_set_rkey(AsyncSock * sock, const unsigned char * key, int keylen) {
	_p_asn_sock_rc4_set_rkey(sock, key, keylen);
}

//----------------------------------------------------------------------
// export: asn_sock_nodelay
//----------------------------------------------------------------------
ANETAPI int asn_sock_nodelay(AsyncSock * sock, int nodelay) {
	return _p_asn_sock_nodelay(sock, nodelay);
}

//----------------------------------------------------------------------
// export: asn_sock_sys_buffer
//----------------------------------------------------------------------
ANETAPI int asn_sock_sys_buffer(AsyncSock * sock, long rcvbuf, long sndbuf) {
	return _p_asn_sock_sys_buffer(sock, rcvbuf, sndbuf);
}

//----------------------------------------------------------------------
// export: asn_sock_keepalive
//----------------------------------------------------------------------
ANETAPI int asn_sock_keepalive(AsyncSock * sock, int keepcnt, int idle, int intvl) {
	return _p_asn_sock_keepalive(sock, keepcnt, idle, intvl);
}


